---
name: Business-PVMForImportAfterExport
version: 0.04
author:
  - 'Gernot Havranek <havi@cpan.org>'
abstract: a module for Postversandmanager in Austria
license: perl
build_requires:
  Test::More: 0
requires:
  perl: v5.10.0
configure_requires:
  Module::Build: 0.340201
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
provides:
  Business::PVMForImportAfterExport:
    file: lib/Business/PVMForImportAfterExport.pm
    version: 0.04
resources:
  license: http://dev.perl.org/licenses/
